# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1aeff9db1367347f8d8457b5f8dafd485f5186f22f1430cdacdb168e0c7c428bbf99d3610cf71065aeeef0b3a7e24e5a69b80cf0d58b359f3bb20f42dacbf07

test:
  secret_key_base: 908102562e2f89e20393530173f60bfa26697b02aa794a8db646c28ad064cb06f0ce60bc80ee5f781e11b08e2022d080643c6ecd52772a561d12d940c8efd68a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
